### ISSUE TITLE
Comment on offspring production

### ISSUE THREAD

**Issue by guillaumeboehm** [jdisset/gaga#6]
https://github.com/jdisset/gaga/blob/9e0c8e49c057aa3ee4704cfb63955dbd7e648170/gaga.hpp#L686

I'm not very sure, but in this line wouldn't it be safer to set the minimum to 1*nbObjectives ? Even though the nOffspring shouldn't be less than 1 to begin with I guess.

**Comment by jdisset** [comment]
This is executed for each objective, so you just want at least one offspring per objective. Which means the total will be >= nbObjectives. I believe this is the correct & expected behavior!
